I+00000.047: Windows-10-10.0.19044 AMD64
             CPython 3.9.17+ (64-bit)
             debugpy 1.6.7

I+00000.047: Initial environment:
             
             System paths:
                 sys.executable: D:\repos\github\feeefeee\debugpy11\src\app1\x64\Debug\app1.exe
                 sys.prefix: C:\Python\Python39
                 sys.base_prefix: C:\Python\Python39
                 sys.real_prefix: <missing>
                 site.getsitepackages(): C:\Python\Python39
                                         C:\Python\Python39\lib\site-packages(C:\Python\Python39\Lib\site-packages)
                 site.getusersitepackages(): C:\Users\philippe.crassous\AppData\Roaming\Python\Python39\site-packages
                 sys.path (site-packages): C:\Python\Python39\lib\site-packages(C:\Python\Python39\Lib\site-packages)
                 sysconfig.get_path('stdlib'): C:\Python\Python39\Lib
                 sysconfig.get_path('platstdlib'): C:\Python\Python39\Lib
                 sysconfig.get_path('purelib'): C:\Python\Python39\Lib\site-packages
                 sysconfig.get_path('platlib'): C:\Python\Python39\Lib\site-packages
                 sysconfig.get_path('include'): C:\Python\Python39\Include(C:\Python\Python39\include)
                 sysconfig.get_path('scripts'): C:\Python\Python39\Scripts
                 sysconfig.get_path('data'): C:\Python\Python39
                 os.__file__: C:\Python\Python39\Lib\os.py
                 threading.__file__: C:\Python\Python39\Lib\threading.py
                 debugpy.__file__: C:\Python\Python39\lib\site-packages\debugpy\__init__.py(C:\Python\Python39\Lib\site-packages\debugpy\__init__.py)

D+00000.047: configure({'python': 'c:/Python/Python39/python.exe'}, {})

D+00000.047: listen(('127.0.0.1', 5678), **{})

I+00000.047: Initial debug configuration: {
                 "qt": "none",
                 "subProcess": true,
                 "python": "c:/Python/Python39/python.exe",
                 "pythonEnv": {}
             }

I+00000.063: Waiting for adapter endpoints on 127.0.0.1:49751...

I+00000.063: debugpy.listen() spawning adapter: [
                 "c:/Python/Python39/python.exe",
                 "C:\\Python\\Python39\\lib\\site-packages\\debugpy\\adapter",
                 "--for-server",
                 "49751",
                 "--host",
                 "127.0.0.1",
                 "--port",
                 "5678",
                 "--server-access-token",
                 "bf9deeb01e6df9228674339c879032107353e951ce8044a1d5d13dab7bbf2c1b",
                 "--log-dir",
                 "c:/tmp"
             ]

I+00000.266: Endpoints received from adapter: {
                 "client": {
                     "host": "127.0.0.1",
                     "port": 5678
                 },
                 "server": {
                     "host": "127.0.0.1",
                     "port": 49752
                 }
             }

I+00000.266: Adapter is accepting incoming client connections on 127.0.0.1:5678

D+00000.266: pydevd.settrace(*(), **{'host': '127.0.0.1', 'port': 49752, 'wait_for_ready_to_run': False, 'block_until_connected': True, 'access_token': 'bf9deeb01e6df9228674339c879032107353e951ce8044a1d5d13dab7bbf2c1b', 'suspend': False, 'patch_multiprocessing': True, 'dont_trace_start_patterns': ('C:\\Python\\Python39\\lib\\site-packages\\debugpy',), 'dont_trace_end_patterns': ('debugpy_launcher.py',)})

I+00000.391: pydevd is connected to adapter at 127.0.0.1:49752

D+00000.391: wait_for_client()

